services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: julens_db
      MYSQL_USER: julens
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: